repos:
- repo: https://github.com/psf/black
  rev: 23.11.0
  hooks:
  - id: black
    name: black
    description: "Black: The uncompromising Python code formatter"
    entry: black
    language: python
    language_version: python3
    minimum_pre_commit_version: 2.9.2
    require_serial: true
    types_or: [python, pyi]

- repo: https://github.com/pycqa/flake8
  rev: 6.1.0
  hooks:
  - id: flake8
    # args: [--select=B028]
    args: [
      # --select=B028,
      "--extend-ignore=E722,B001"
    ]
    additional_dependencies:
    - flake8-bugbear
    - flake8-comprehensions
    - flake8-simplify

- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/PyCQA/isort
  rev: 5.12.0
  hooks:
  - id: isort
    files: \.py$

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-builtin-literals
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-toml
    - id: check-yaml
      exclude: |
          (?x)^(
              conda/meta.yaml
          )
    - id: debug-statements
    - id: end-of-file-fixer
    - id: forbid-new-submodules
    - id: mixed-line-ending
    - id: trailing-whitespace

- repo: https://github.com/regebro/pyroma
  rev: "4.2"
  hooks:
  - id: pyroma
    args: ["-d", "--min=10", "."]

# - repo: https://github.com/mgedmin/check-manifest
#   rev: "0.49"
#   hooks:
#   - id: check-manifest
#     args: ["--ignore=.nox,build", "--no-build-isolation"]

# - repo: https://github.com/PyCQA/pydocstyle
#   rev: 6.3.0
#   hooks:
#   - id: pydocstyle
#     files: landlab/.*\.py$
#     args:
#     - --convention=numpy
#     - --add-select=D417
#     additional_dependencies: [".[toml]"]
